YearOfProgramming/2017Challenges

challenge_0/python/mjuiuc/README.md, challenge_0/python/mjuiuc/helloworld.py
Here ya go.. So this is why people use github so heavily lol.
=> first challenge completed

challenge_0/python/alexmunoz905/main.py
The Pull Request with “Hello, world!” written in python
=> pull request with python

challenge_1/README.md
=> first actual challenge

challenge_0/php/selectivealso/readme.md
Adds a readme.md for php/selectivealso
=> Adds a readme.md for php/selectivealso

challenge_0/python/alexmunoz905/readme.md
=> Add readme.md to alexmunoz905

challenge_0/python/challenge_0.py, challenge_0/python/lex32pem/challenge_0.py, challenge_0/python/lex32pem/readme.md
=> challenge_0

challenge_3/README.md
=> updated c3 example

challenge_2/rust/josephpd3/Cargo.lock, challenge_2/rust/josephpd3/Cargo.toml, challenge_2/rust/josephpd3/README.md, challenge_2/rust/josephpd3/src/lib.rs, challenge_2/rust/josephpd3/tests/single_count.rs
Docs, Source, and Tests included!
=> Lonely Characters Club (Challenge 2 Solution in Rust)

challenge_0/javascript/raijinn/README.md, challenge_0/javascript/raijinn/src/challenge_0.js, challenge_1/javascript/raijinn/README.md, challenge_1/javascript/raijinn/src/challenge_1.js
Completed challenges written in JavaScript.
=> Submitting challenges in JavaScript

challenge_1/python/DakRomo/main.py
Reverts YearOfProgramming/2017Challenges#78
=> Revert "Update main.py"

challenge_0/README.md, challenge_0/python/phil-harmoniq/challenge_0.py, challenge_1/python/phil-harmoniq/challenge_1.py, challenge_2/python/phil-harmoniq/README.md, challenge_2/python/phil-harmoniq/challenge_2.py, challenge_3/python/phil-harmoniq/challenge_3.py
Submitting challenges 0-3. I also found 2 typos in the challenge_0 readme.
=> Hello world!

challenge_0/cpp/chowey/main.cpp, challenge_0/cpp/chowey/readme.md
=> challenge_0 in cpp

challenge_0/x86/x95/README.md, challenge_0/x86/x95/src/helloworld.s
=> challenge_0 in x86asm

challenge_0/haskell/halogenandtoast/README.md, challenge_0/haskell/halogenandtoast/src/Main.hs
=> Haskell Hello World

challenge_2/python/lex32pem/Readme.md, challenge_2/python/lex32pem/challenge_2.py
=> challenge_2

challenge_0/c/boilerup_brian/README.md, challenge_0/c/boilerup_brian/helloWorld.c
boilerup_brian, challenge 0 in C
=> Challenge 0

challenge_0/python/OkraArmband/README.md, challenge_0/python/OkraArmband/src/hello_world.py, challenge_1/python/OkraArmband/README.md, challenge_1/python/OkraArmband/src/reverse.py, challenge_2/python/OkraArmband/README.md, challenge_2/python/OkraArmband/src/unique_ele.py
I did the thing! Comments/criticism welcome!
=> Challenges 0, 1, and 2 in Python

challenge_1/haskell/halogenandtoast/README.md, challenge_1/haskell/halogenandtoast/src/Main.hs
=> Challenge 1: Haskell

challenge_2/r/henriquefb/README.md, challenge_2/r/henriquefb/challenge2hfb.R
Comments and suggestions, if any, are appreciated. Thank you mods for the great work!
=> challenge_2 in R

Unittesting.md
Adding a short doc on unit testing in python.
=> lil unit testing doc

challenge_0/python/mindm/README.md, challenge_0/python/mindm/src/hello.py
=> Challenge_0 in python

challenge_0/python/slandau/README.md, challenge_0/python/slandau/hello_world.py
My first contribution to the year of code programming challenge.
=> Challenge 0 in python

challenge_0/python/slandau/README.md, challenge_0/python/slandau/hello_world.py, challenge_1/python/slandau/README.md, challenge_1/python/slandau/reverse.py, challenge_2/python/slandau/README.md, challenge_2/python/slandau/single.py, challenge_3/python/slandau/README.md, challenge_3/python/slandau/majority.py
Just finished challenge 1, both recursively and iteratively. Not sure why it's uploading challange_0 again along with it.
=> [Python] Challenge 1,2 and 3

README.md
Fixed typo on line 233 of Project Readme
=> Fixed typo on line 233 of Project Readme

challenge_6/README.md, challenge_6/python/slandau3/ranges.py, challenge_6/python/slandau3/tests.py
=> Challenge 6

challenge_1/python/mindm/README.md, challenge_1/python/mindm/src/reverse.py
Nothing much to say. I prefer the command-line interface with arguments.
=> [python] Challenge 1 (Unreviewed)

challenge_1/python/jcpattison/README.md, challenge_1/python/jcpattison/src/reverse.py
=> [Python] Challenge 1

challenge_0/python/CindyB/README.md, challenge_0/python/CindyB/src/helloworld.py, challenge_1/python/CindyB/README.md, challenge_1/python/CindyB/src/reverse_string.py, challenge_1/python/CindyB/src/reverse_string_test.py
I tried some unit tests based on the useful example in the repo.
=> [Python] Challenge #1 (Unreviewed)

challenge_1/python/alexbotello/README.md, challenge_1/python/alexbotello/main.py, challenge_2/python/alexbotello/README.md, challenge_2/python/alexbotello/main.py, challenge_3/python/alexbotello/README.md, challenge_3/python/alexbotello/main.py
=> [Python] Challenge 1, 2 and 3 (Pending)

challenge_1/cpp/chowey/main.cpp, challenge_1/cpp/chowey/readme.md
Solution for Reversing a String
=> [C++] Challenge 1 (Pending)

challenge_0/julia/DTCitron/README.md, challenge_0/julia/DTCitron/src/helloworld.jl, challenge_0/python/DTCitron/README.md, challenge_0/python/DTCitron/src/main.py
Completed Challenge 0 in Julia
(also in Python)
=> [Julia] challenge_0

challenge_0/go/natdm/app.go, challenge_1/go/natdm/reverse.go, challenge_1/go/natdm/reverse_test.go, challenge_2/go/natdm/single.go, challenge_2/go/natdm/single_test.go, challenge_3/go/natdm/majority.go, challenge_3/go/natdm/majority_test.go, challenge_4/go/natdm/tree.go, challenge_4/go/natdm/tree_test.go, challenge_5/go/natdm/diff.go, challenge_5/go/natdm/diff_test.go
=> [Go] Challenge 0-5 (Unreviewed)

challenge_5/python/ning/FindTheDifference.py, challenge_5/python/ning/README.md
This solution uses the in-built `Counter` object from the `collections` module. 
We count the identity and occurence of letters in the strings s and t, then compare them. The odd letter out of the two is returned.
=> [Python] Challenge #5 (Unreviewed)

challenge_7/python/Loran425/README.md, challenge_7/python/Loran425/src/missing.py, challenge_7/python/Loran425/src/tests.py
Challenge_7 solution with some git shenanigans
=> [Python] Challenge 7 (Ready to Merge)

challenge_3/python/mindm/README.md, challenge_3/python/mindm/src/majority.py
Based pretty much on the last challenge.
=> [Python] Challenge 3 (Pending)

challenge_7/c/karanchawla/README.md, challenge_7/c/karanchawla/missingNumber.c
Implemented Challenge #7 in C.
=> [C] Challenge #7

challenge_3/r/henriquefb/README.md, challenge_3/r/henriquefb/challenge3hfb.R
Solution to challenge 3 using R. As always, comments and suggestions from the community as a whole are well appreciated. Thank you mods for your work!
=> [R] Challenge 3 (Unreviewed)

challenge_3/C/karanchawla/src/README.md, challenge_3/C/karanchawla/src/majElement.c, challenge_9/C/karanchawla/src/README.md, challenge_9/C/karanchawla/src/challenge9.c
Completed the challenge in C, implemented Counting Sort (feels like cheating) but will update this if I think of an alternate solution.  
Also implemented Moore's Voting algorithm for Challenge 3.
=> [ C ] Challenge #9 (Unreviewed)

challenge_2/python/mindm/README.md, challenge_2/python/mindm/src/single.py
First I tried to parse the input as JSON but it didn't quite work in the extra credit feature unless you escaped the quotes which seemed ugly.
=> [python] Challenge 2 (ReadyToMerge)

challenge_9/python/alexbotello/README.md, challenge_9/python/alexbotello/src/square.py, challenge_9/python/alexbotello/src/test.py
This one took me awhile and probably would of taken longer if not for the discussion on slack :)
=> [Python] Challenge 9 (ReadyForMerge)

challenge_8/python/Loran425/README.md, challenge_8/python/Loran425/src/linked_list.py
I dislike randomly linked lists now. double linked or single linked are so much easier.
=> [Python] Challenge #8 (Unreviewed)

challenge_0/cpp/sven/README.md, challenge_0/cpp/sven/src/HelloWorld.cpp, challenge_0/csharp/sven/README.md, challenge_0/csharp/sven/src/HelloWorld.cs, challenge_1/cpp/sven/README.md, challenge_1/cpp/sven/src/Reverse.cpp, challenge_1/csharp/sven/README.md, challenge_1/csharp/sven/src/Reverse.cs, challenge_2/cpp/sven/README.md, challenge_2/cpp/sven/src/Single.cpp, challenge_2/csharp/sven/README.md, challenge_2/csharp/sven/src/Single.cs
I've separated all solutions into their own commits
=> [c++] [c#] Challenges 0, 1 & 2

challenge_11/python/mindm/README.md, challenge_11/python/mindm/src/btree.py, challenge_11/python/mindm/src/remove_from_tree.py
I created a bit easier to read print than preorder print. You read it like this:
```
root
left node of root
left node of parent
- (empty)
- (empty)
right node of parent
- (empty)
- (empty)
right node of root
etc...
``` 
I used `5 3 7 2 4 6 8` input to test all remove cases and they worked.
=> [Python] Challenge 11 (ReadyForMerge)

challenge_0/bash/ning/README.md, challenge_0/bash/ning/challenge_0.sh
Nothing much to comment here...
=> [Bash] Challenge #0 (Unreviewed)

challenge_0/python/dfdx2/hello.py
Python Challenge 0 Submission for review
=> [Python] Challenge 0 (Unreviewed)

challenge_0/c/xor-eax-eax/README.md, challenge_0/c/xor-eax-eax/src/challenge0.c
Submitting C challenge 0 for review.
=> C Challenge 0 (Unreviewed)

challenge_10/python/alexbotello/README.md, challenge_10/python/alexbotello/src/closers.py, challenge_10/python/alexbotello/src/tests.py
For this challenge we implement a list as a stack. As we iterate through the
string input we add every opener found into the stack sequentially.
As the iteration continues onto the closers, check the if closer matches the last
element in our stack. If match is successful, pop the element off the stack and continue.
If any pair fails to match then the string input contains an invalid closer and
the function returns False.
After iteration is complete if our stack is empty then every opener had a valid
closer and the function returns True.
=> [Python] Challenge 10 (ReadyForMerge)

challenge_2/python/dfdx2/count.py
=> [Python] Challenge 2 (Unreviewed)

challenge_0/java/JakeBash/Challenge_0.java
Challenge 0 completed in Java (Unreviewed)
=> [Java] Challenge 0 (Unreviewed)

challenge_1/java/JakeBash/Challenge_1.java
Completed Challenge 1 in the Java programming language.
=> [Java] Challenge 1 (Unreviewed)

challenge_1/c/xor-eax-eax/README.md, challenge_1/c/xor-eax-eax/src/challenge1.c
Not sure if the following belongs in the pull request, let me know if it doesn't.
=> C Challenge 1 (Unreviewed)

challenge_13/python/ning/README.md, challenge_13/python/ning/challenge_13.py, challenge_13/python/ning/test.py
1. We run through conditionals to check for non-palindromic integers. If they pass these tests, we assume them to be palindromic.
2. Single-digit integers are by definition (of this challenge, anyway) palindromes. These skip the main `while` loop and the function returns True straight away. For the rest...
3. First, we store the last digit (in the ones position) in the variable `ones`. In this process, the last digit of the given integer is also made to be zero.
4. Assuming the given integer is palindromic, we subtract the first digit, hence removing it. Next, divide the integer by 10 to remove the last integer. Hence, two digits from each end of the given integer is stripped off. Following this, there are 4 cases to consider.
_Case 1_: 514 -> 11
In this non-palindromic case, we end up …
=> [Python] Challenge #13 (Unreviewed)

challenge_2/Java/JakeBash/Challenge_2.java
Completed Challenge #2 in the Java programming language
=> [Java] Challenge 2 (Unreviewed)

challenge_0/csharp/jfrancis2/README.md, challenge_0/csharp/jfrancis2/src/hello.cs
First attempt at pull request.
=> [C#] Challenge 0 (Unreviewed)

challenge_0/python/Fejolu/readme.md, challenge_0/python/Fejolu/src/helloworld.py
[Python] Challenge 0 (Unreviewed)
=> [Python] Challenge 0 (ReadyForMerge)

challenge_1/cpp/alexbotello/README.md, challenge_1/cpp/alexbotello/src/main.cpp
Iterates through string input starting from the last element. For every element output it to screen.
=> [C++] Challenge 1 (ReadyForMerge)

challenge_4/python/dfdx2/README.md, challenge_4/python/dfdx2/binary1.py
Python Challenge 4 submission unreviewed
=> [Python] Challenge #4 (Unreviewed)

challenge_18/C/yourpalnurav/README.md, challenge_18/C/yourpalnurav/YPN_Paths.c
=> [C] Challenge 18 (Pending)

challenge_3/python/dfdx2/challenge_3.py
=> [Python] Challenge 3 (Unreviewed)

challenge_2/c/xor-eax-eax/README.md, challenge_2/c/xor-eax-eax/src/challenge2.c
Just realized challenges are asking things to be generic and not hardcoded, will update in the future.
=> C Challenge 2 (Unreviewed)

challenge_0/fsharp/mssabr01/README.md, challenge_0/fsharp/mssabr01/src/HelloWorld.fs
Hello!
This is my first pull request and my hands are sweating :)
=> fsharp Challenge 0 (Unreviewed)
